spring.application.name=climalert

weather-api.base-url=https://api.weatherapi.com
weather-api.api-key=${WEATHER_API_API_KEY:}

ciudad-consulta=Buenos Aires

resend.api_key=${RESEND_API_KEY:}
resend.from_email=${RESEND_FROM_EMAIL:}

correos-destino=admin@clima.com emergencias@clima.com meteorologia@clima.com
